spring:
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      enabled: true
      config:
        enabled: true
        format: YAML
        watch:
          wait-time: 15
          delay: 5000
  application:
    name: ${app.name}
logging:
  level:
    root: DEBUG

api:
  key: DVZTXfc5794l69kip1hIy6xl77RqPmQ7

app:
  name: currency-generator
server:
  port: 8081
